/*
 * Virtual Wallet
 * API for the Product iWallet
 *
 * OpenAPI spec version: 2.10.35
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.interblocks.iwallet.smb.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.ToString;

import java.util.ArrayList;
import java.util.List;

/**
 * User
 */
@Data
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-09-17T14:19:47.887Z")
public class ModelUser {
    @JsonProperty("email")
    private String email = null;

    @JsonProperty("firstName")
    private String firstName = null;

    @JsonProperty("lastName")
    private String lastName = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("userName")
    private String userName = null;

    @JsonProperty("password")
    @ToString.Exclude
    private String password = null;

    @JsonProperty("mobile")
    private String mobile = null;

    @JsonProperty("nicNumber")
    private String nicNumber = null;

    @JsonProperty("gender")
    private String gender = null;

    @JsonProperty("dob")
    private String dob = null;

    @JsonProperty("nationality")
    private String nationality = null;

    @JsonProperty("country")
    private String country = null;

    @JsonProperty("streetNo")
    private String streetNo = null;

    @JsonProperty("city")
    private String city = null;

    @JsonProperty("passport")
    private String passport = null;

    @JsonProperty("bankCode")
    private String bankCode = null;

    @JsonProperty("validationCode")
    private String validationCode = null;

    @JsonProperty("securityImages")
    private String securityImages = null;

    @JsonProperty("userID")
    private String userID = null;

    @JsonProperty("registrationProcess")
    private UserRegistrationProcess registrationProcess = null;

    @JsonProperty("imageUrl")
    private String imageUrl = null;

    @JsonProperty("merchantNumber")
    private String merchantNumber = null;

    @JsonProperty("merchantEnable")
    private Boolean merchantEnable = null;

    @JsonProperty("agentEnable")
    private Boolean agentEnable = null;

    @JsonProperty("merchantAccountID")
    private String merchantAccountID = null;

    @JsonProperty("deviceIdentifier")
    private List<String> deviceIdentifier = null;

    @JsonProperty("kycApproved")
    private Boolean kycApproved = null;

    @JsonProperty("forcePassword")
    private Boolean forcePassword = null;

    @JsonProperty("tocStatus")
    private Boolean tocStatus = null;

    @JsonProperty("registrationDate")
    private String registrationDate = null;

    @JsonProperty("UserKYCList")
    private List<KYC> userKYCList = null;

    @JsonProperty("MerchantKYCList")
    private List<KYC> merchantKYCList = null;

    @JsonProperty("AgentKYCList")
    private List<KYC> agentKYCList = null;

    public ModelUser addAgentKYCListItem(KYC agentKYCListItem) {
        if (this.agentKYCList == null) {
            this.agentKYCList = new ArrayList<KYC>();
        }
        this.agentKYCList.add(agentKYCListItem);
        return this;
    }

    public ModelUser addDeviceIdentifierItem(String deviceIdentifierItem) {
        if (this.deviceIdentifier == null) {
            this.deviceIdentifier = new ArrayList<String>();
        }
        this.deviceIdentifier.add(deviceIdentifierItem);
        return this;
    }

    public ModelUser addUserKYCListItem(KYC userKYCListItem) {
        if (this.userKYCList == null) {
            this.userKYCList = new ArrayList<KYC>();
        }
        this.userKYCList.add(userKYCListItem);
        return this;
    }

    public ModelUser addMerchantKYCListItem(KYC merchantKYCListItem) {
        if (this.merchantKYCList == null) {
            this.merchantKYCList = new ArrayList<KYC>();
        }
        this.merchantKYCList.add(merchantKYCListItem);
        return this;
    }
}

