/*
 * Virtual Wallet
 * API for the Product iWallet
 *
 * OpenAPI spec version: 2.10.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.interblocks.iwallet.smb.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.ToString;

import java.math.BigDecimal;

/**
 * PostUser
 */
@Data
//@ToString
//@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-30T08:37:57.949Z")
public class PostUser {
    @JsonProperty("sessionID")
    private String sessionID = null;

    @JsonProperty("firstName")
    private String firstName = null;

    @JsonProperty("lastName")
    private String lastName = null;

    @JsonProperty("email")
    private String email = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("userName")
    private String userName = null;

    @ToString.Exclude
    @JsonProperty("password")
    private String password = null;

    @JsonProperty("gender")
    private String gender = null;

    @JsonProperty("dob")
    private BigDecimal dob = null;

    @JsonProperty("nationality")
    private String nationality = null;

    @JsonProperty("country")
    private String country = null;

    @JsonProperty("streetNo")
    private String streetNo = null;

    @JsonProperty("city")
    private String city = null;

    @JsonProperty("passport")
    private String passport = null;

    @JsonProperty("mobile")
    private String mobile = null;

    @JsonProperty("nicNumber")
    private String nicNumber = null;

    @ToString.Exclude
    @JsonProperty("validationCode")
    private String validationCode = null;

    @JsonProperty("deviceID")
    private String deviceID = null;

    @JsonProperty("deviceInfo")
    private LoginUserDeviceInfo deviceInfo = null;

    @JsonProperty("socialUser")
    private SocialUser socialUser = null;
}

