/*
 * Virtual Wallet
 * API for the Product iWallet
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.interblocks.iwallet.smb.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SocialUser
 */
//@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-06-03T09:57:21.685Z")
public class SocialUser {
    @JsonProperty("authToken")
    private String authToken = null;

    @JsonProperty("email")
    private String email = null;

    @JsonProperty("firstName")
    private String firstName = null;

    @JsonProperty("lastName")
    private String lastName = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("id")
    private String id = null;

    @JsonProperty("idToken")
    private String idToken = null;

    @JsonProperty("photoUrl")
    private String photoUrl = null;

    @JsonProperty("provider")
    private String provider = null;

    public SocialUser authToken(String authToken) {
        this.authToken = authToken;
        return this;
    }

    /**
     * Get authToken
     *
     * @return authToken
     **/
    @JsonProperty("authToken")
    @ApiModelProperty(value = "")
    public String getAuthToken() {
        return authToken;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    public SocialUser email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     *
     * @return email
     **/
    @JsonProperty("email")
    @ApiModelProperty(value = "")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public SocialUser firstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Get firstName
     *
     * @return firstName
     **/
    @JsonProperty("firstName")
    @ApiModelProperty(value = "")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public SocialUser lastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Get lastName
     *
     * @return lastName
     **/
    @JsonProperty("lastName")
    @ApiModelProperty(value = "")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public SocialUser name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @JsonProperty("name")
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SocialUser id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @JsonProperty("id")
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SocialUser idToken(String idToken) {
        this.idToken = idToken;
        return this;
    }

    /**
     * Get idToken
     *
     * @return idToken
     **/
    @JsonProperty("idToken")
    @ApiModelProperty(value = "")
    public String getIdToken() {
        return idToken;
    }

    public void setIdToken(String idToken) {
        this.idToken = idToken;
    }

    public SocialUser photoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
        return this;
    }

    /**
     * Get photoUrl
     *
     * @return photoUrl
     **/
    @JsonProperty("photoUrl")
    @ApiModelProperty(value = "")
    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public SocialUser provider(String provider) {
        this.provider = provider;
        return this;
    }

    /**
     * Get provider
     *
     * @return provider
     **/
    @JsonProperty("provider")
    @ApiModelProperty(value = "")
    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SocialUser socialUser = (SocialUser) o;
        return Objects.equals(this.authToken, socialUser.authToken) &&
                Objects.equals(this.email, socialUser.email) &&
                Objects.equals(this.firstName, socialUser.firstName) &&
                Objects.equals(this.lastName, socialUser.lastName) &&
                Objects.equals(this.name, socialUser.name) &&
                Objects.equals(this.id, socialUser.id) &&
                Objects.equals(this.idToken, socialUser.idToken) &&
                Objects.equals(this.photoUrl, socialUser.photoUrl) &&
                Objects.equals(this.provider, socialUser.provider);
    }

    @Override
    public int hashCode() {
        return Objects.hash(authToken, email, firstName, lastName, name, id, idToken, photoUrl, provider);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SocialUser {\n");

        sb.append("    authToken: ").append(toIndentedString(authToken)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
        sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    idToken: ").append(toIndentedString(idToken)).append("\n");
        sb.append("    photoUrl: ").append(toIndentedString(photoUrl)).append("\n");
        sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

