/*
 * Virtual Wallet
 * API for the Product iWallet
 *
 * OpenAPI spec version: 2.8.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.interblocks.iwallet.smb.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

//import io.swagger.annotations.ApiModelProperty;

/**
 * UserRegistrationProcess
 */

public class UserRegistrationProcess {
    @JsonProperty("completed")
    private Boolean completed = null;

    @JsonProperty("step")
    private String step = null;

    public UserRegistrationProcess completed(Boolean completed) {
        this.completed = completed;
        return this;
    }

    /**
     * Get completed
     *
     * @return completed
     **/
    @JsonProperty("completed")
//    @ApiModelProperty(example = "false", value = "")
    public Boolean isCompleted() {
        return completed;
    }

    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    public UserRegistrationProcess step(String step) {
        this.step = step;
        return this;
    }

    /**
     * Get step
     *
     * @return step
     **/
    @JsonProperty("step")
//    @ApiModelProperty(example = "registered", value = "")
    public String getStep() {
        return step;
    }

    public void setStep(String step) {
        this.step = step;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserRegistrationProcess userRegistrationProcess = (UserRegistrationProcess) o;
        return Objects.equals(this.completed, userRegistrationProcess.completed) &&
                Objects.equals(this.step, userRegistrationProcess.step);
    }

    @Override
    public int hashCode() {
        return Objects.hash(completed, step);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserRegistrationProcess {\n");

        sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
        sb.append("    step: ").append(toIndentedString(step)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

