#This is default to all services

android:
  signatures: 24234234234234
api-ipg:
  log:
    file: F:/Data/iWallet/logs/api-ipg.log
    level: DEBUG
    pattern: F:/Data/iWallet/logs/api-ipg-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
api-partners:
  log:
    file: F:/Data/iWallet/logs/api-partners.log
    level: DEBUG
    pattern: F:/Data/iWallet/logs/api-partners-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
api-inapp:
  log:
    file: F:/Data/iWallet/logs/api-inapp.log
    level: DEBUG
    pattern: F:/Data/iWallet/logs/api-inapp-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
api:
  access-control-allow-headers: Content-Type, Accept, authorization
  access-control-allow-methods: GET, POST, DELETE, PATCH
  access-control-allow-origin: '*'
  cardsEnabled: true
  tamEnabled: true
  walletsEnabled: true
backoffice:
  access-control-allow-headers: Content-Type
  access-control-allow-methods: GET, POST, DELETE, PUT
  access-control-allow-origin: '*'
  log:
    file: F:/Data/iWallet/logs/backoffice.log
    level: DEBUG
    pattern: F:/Data/iWallet/logs/backoffice-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
biller:
  data:
    ref: Receipt NR
broker:
  client-id: clientIdOne
  client-secret: clientSecretOne
  ip: 192.168.1.200
  port: 2125
  xml-processor:
   classes: com.interblocks.webtools.broker.model.core.DefaultRequest, com.interblocks.webtools.broker.model.core.DefaultResponse, com.interblocks.webtools.broker.model.card.BalanceInquiryResponse, com.interblocks.webtools.broker.model.transaction.TrxMsg, com.interblocks.webtools.broker.model.billutility.BillCommonResponse, com.interblocks.webtools.broker.model.transactioninquiry.TransactionInquiryResponse, com.interblocks.webtools.broker.model.externalutility.ExtCommonResponse
config:
  ipin:
    response-url: http://pg-test.tamhere.com/ipin/Complete.jsp
    url: http://pg-test.tamhere.com/ipin/request.pin
database:
  iadmin:
    username: IBL_D_USR
  iwallet:
    classname: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.131:1521:devdb
    username: IBL_D_BNK
  service-broker:
    enabled: false
dbpwd_server:
  ip: 192.168.1.4
  port: 65531
  read_buffer_size: 2048
  read_timeout: 30000
  write_timeout: 5000
default:
  acquirerId: 405635
  bank_code: '0001'
  bank_name: Hitachi
  branch_code: '00000'
  callCenterNo: 80008778
  country_code: '094'
  currCode: '144'
  currDesc: LKR
  exponential: 100
  locationTag: HCE______ IWALLET      _________     LKA
  max:
    random_amount: 200000
  merchantId: 300800000000000
  messageGroupId: 40
  min:
    random_amount: 10000
  product_id: WLT
  random_amount: 20000
  sender: wallet
  service_user: iWalletService
  terminalId: 5613800000000000
  aux: true
dns:
  iwallet:
    nameservers: 8.8.8.8
    #provider:
      #1: dns,sun
      #2: default
file_server:
  file:
    extensions: xls,jpg
    root_path: F:/Projects/WLT/iwallet/assets
    temp_path: F:/Projects/WLT/iwallet/assets/temp
  image:
    extensions: jpg
    root_path: F:/Projects/WLT/iwallet/assets
    temp_path: F:/Projects/WLT/iwallet/assets/temp
  root_path: F:/Projects/WLT/iwallet/assets
firebase:
  app_icon_url: https://firebasestorage.googleapis.com/v0/b/virtual-wallet-35f89.appspot.com/o/notification%2Ficon.png?alt=media&token=ddc75d50-6803-4f6c-a4a7-4b9876d3cad7
  dynamiclink:
    prefix: https://iwallet.page.link/?link=
    url: https://firebasedynamiclinks.googleapis.com/v1/shortLinks
  fcm:
    auth_key: AAAAlwFm5Ts:APA91bHYMisielTsu5CXJRcIyrlrWSvKIVi_60dOAbPSUzL9hNTSxIhZsaWKYMo0vJRC5dYhXOqugln4r-76olJQGrhGaaVS1YpmE8bfwVzQFZq9Q4IZnuSQuFyXsTt5vpnkq1eXZAJM
    url: https://fcm.googleapis.com/fcm/send
  proxy:
    enable: false
  service:
    config_path: /apps/qa/ibl/lmr/app/cmn/pie-iwallet-firebase-adminsdk-yibf4-7efe561613.json
    key: AIzaSyBUGgBpgH7aHsSZ9oAAYSG-c7EGYTjN6o4
    url: firebase-adminsdk-yibf4@pie-iwallet.iam.gserviceaccount.com
flag:
  BILL_PAYMENTS_RECEIPT: true
  FUND_RECEIVED_RECEIPT: true
  FUND_SENT_RECEIPT: true
  SOCIAL_PAYMENTS_RECEIVED: true
  SOCIAL_PAYMENTS_SENT: true
hibernate:
  dialect: org.hibernate.dialect.OracleDialect
  hbm2ddl:
    auto: none
  show_sql: true
hikari:
  max_life_time: 1800000
  max_pool_size: 5
iadmin:
  bill:
    service_url: http://192.168.1.4:8080/iAdmin/rest/utilityProviderServices
    walletRef: WALLET
  rest:
    service_url: http://192.168.1.4:8080/iAdmin/rest/WalletService
    user_service_url: http://192.168.1.4:8080/iAdmin/rest/userServices
    utility:
      url: http://192.168.1.4:8080/iAdmin/rest/utilityServices
    v2:
      url: http://192.168.1.4:8080/iAdmin/rest/RestAuthManagementV2
  soap:
    inapp_url: http://192.168.1.4:8080/iAdmin/AuthManagement?wsdl
    service_url: http://192.168.1.4:8080/iAdmin/AuthManagementV2?wsdl
icard:
  product_id: PRD665
  rest:
    account_balance_inquiry: http://192.168.1.4:8080/icard/rest/InternalFunctionService/AccountInquiry
    account_list_inquiry: http://192.168.1.4:8080/icard/rest/InternalFunctionService/AccountInquiry
    card_service_url: http://172.16.8.25:9501/api/v1/card/api/card
    cust_inquiry_url: http://192.168.1.4:8080/icard/rest/CrdCustomerService/CustomerInquiryFromWallet
    link_card_url: http://192.168.1.4:8080/icard/rest/CrdCardService/LinkCardtoCustomer
    pin_change_url: http://192.168.1.4:8080/icard/rest/CrdCardService/PINChangeFromWallet
    pin_nominate_url: http://192.168.1.4:8080/icard/rest/CrdCardService/PINNominateFromWallet
    trxn_inquiry_url: http://192.168.1.4:8080/icard/rest/CrdCommonService/TransactionInquiry
    usr_login_url: http://192.168.1.4:8080/icard/rest/CrdAuthService/UserLogin
    wallet_service_key: 049cf81c-c4ee-4df0-9fcc-c47748775e2e
    wallet_service_url: http://172.16.8.25:9501/api/v1/card/api/wallet
  upgrade_product_id: PRD665
icore:
  merchant_scheme: 00000
  product_type: WalletMerchant
  rest:
    service_url: http://192.168.1.4:8080/icore/rest
icore_core_bank_id: 123
# No Usage
iesb:
  ip: 127.0.0.1
  port: 21340
inapp:
  is_linked_card_to_be_activated: Yes
  link_card_to_user_attempts: 7
  otp_expiry_min: 10
  token_validity_timeout: 3600
ipay:
  rest:
    qr_service_url: https://192.168.1.4:8080/ipg/rest/QRCodeService
ipin:
  soap:
    service_url: http://192.168.1.4:8080/ipin/TokenManager?wsdl
# No Usage
iswitch:
  ip: 127.0.0.1
  port: 50110
iwallet:
  dns:
    name: http://pg-test.tamhere.com
  http:
    timeout: 10000
  reg:
    age_limit_check: false
    field: email
    icard_user_verify: true
    min_age: 18
    upgrade_after_kyc: true
    without:
      kyc: true
  report:
    temp:
      path: F:\\Data\\iWallet\\report\\temp\\
  rest:
    api_base_url: http://localhost:8780
log:
  eureka:
    backup:
      path: ./app-registry/logs
  iwallet:
    backup_path: ./archived/logs/api-iwallet-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
    file: ./logs/api-iwallet.log
    level: DEBUG
    path: ./logs
  zuul:
    backup:
      path: ./gateway/logs
module:
  extention:
    path: /apps/qa/ibl/lmr/app/cmn/iplugins/extentions
pageable:
  max:
    value: 10
  min:
    value: 0
payment:
  json_schema_spec: http://json-schema.org/draft-04/schema#
proxy:
  host: 172.16.8.25
  port: 8080
qr_service:
  ip: 127.0.0.1
  port: 1220
  provider_type: prop
schedule:
  bill:
    pay-job: 0 0/5 * * * ?
scheduler:
  SHD_PAY_INTERVAL_IN_SEC: 86400
  SHD_PAY_START_TIME: 1496741178875
  SHD_SP_INTERVAL_IN_SEC: 600
security:
  jwt:
    expiration: 86400000
session:
  timeout:
    idle: 4320
    validity: 4320
social:
  facebook:
    client_id: clientIdOne
    client_secret: clientSecretOne
    client_validate_url: https://graph.facebook.com/oauth/access_token
    user_validate_url: https://graph.facebook.com/debug_token
  google:
    client_id: 725802639528-t24gjgjjqnf76u1vpjp61undnqif3nf6.apps.googleusercontent.com
    validate_url: https://www.googleapis.com/oauth2/v1/tokeninfo
  share:
    exp-job: 0 0/1 * * * ?
    resources: 
spring:
  thymeleaf:
    prefix: file:/apps/qa/ibl/lmr/app/cmn/wlt/api-iwallet/
swt:
  trx:
    datetime_format: dd/MM/yyyy hh:mm a
    success: 00,000
    # If use BKN view instead of SWT please use these types - 556,391,554,392,395,155,156,162,154,163,124,393,112,128,555,512
    types: 02,182,192,193,155,189,03,183,13,191,186,04,187,181,53,08,188,30,270,271,272,274,280,281,06,14,273,190,284,195,196,83,82,85,87,84,206,119,306,112,87,119,122,109,111,110,113,112,126,127,315,316,317,451
trxn:
  reversal_retry_count: 1
  send_money:
    expiry_timeout: 5
    url: http://pg-test.tamhere.com/gateway/api-iwallet/getsocialpay
walletId:
  db: moblNo
  request: PostUser-mobile,LoginUser-userID
