#This is default profile for api-partners service

# eureka configs
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        ip-address: 127.0.0.1
        
# Hazelcast Config        
hazelcast:
  custom:
    groupName: SAMPATH_DEV
    instanceName: smb_dev_caching_instance
    interfaces: 127.0.0.*
    ips: 127.0.0.1
    logger: log4j
    port: 1055
  logging:
    type: log4j
    
# Configuration for Health endpoint
endpoints:
  health:
    id: health
    enabled: true
    sensitive: false